name: tiktok_env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - ipywidgets
  - ipython
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - transformers
      - tokenizers
      - huggingface-hub
      - hf_xet 
      - streamlit
      - pillow
      - pyarrow
      - tqdm
      - altair
      - safetensors
      - tenacity
      - regex
      - pydeck
      - filelock
      - gitpython
      - protobuf
